name: 'Install D2'
description: 'Installiert das D2 Diagramm-Tool auf verschiedenen Plattformen (Linux, macOS, Windows)'
inputs:
  version:
    description: 'Die zu installierende D2-Version'
    required: false
    default: 'v0.7.0'

runs:
  using: 'composite'
  steps:
    # Linux-Installation
    - name: Install d2 (Linux)
      if: runner.os == 'Linux'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        set -e
        gh release download ${{ inputs.version }} --repo terrastruct/d2 --pattern d2-${{ inputs.version }}-linux-amd64.tar.gz
        cat > sha.txt <<EOM
        6b990f7f65b9f3ea067b19289a75a3a3c44716fb028bb909fbb36036c7437bd9  d2-${{ inputs.version }}-linux-amd64.tar.gz
        EOM
        sha256sum --check sha.txt
        tar xvf d2-${{ inputs.version }}-linux-amd64.tar.gz
        sudo cp d2-${{ inputs.version }}/bin/d2 /usr/local/bin

    # Windows-Installation
    - name: Install d2 (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        $ErrorActionPreference = 'Stop'
        gh release download ${{ inputs.version }} --repo terrastruct/d2 --pattern d2-${{ inputs.version }}-windows-amd64.tar.gz
        $expectedHash = "4aded6f6b1576ab77eb9ff6051254bec42620dd4a5af57fb02e7619f06660ff6"
        $actualHash = (Get-FileHash -Algorithm SHA256 "d2-${{ inputs.version }}-windows-amd64.tar.gz").Hash.ToLower()
        if ($actualHash -ne $expectedHash) {
            throw "SHA256 verification failed!"
        }
        tar xvf d2-${{ inputs.version }}-windows-amd64.tar.gz
        Copy-Item "d2-${{ inputs.version }}/bin/d2.exe" -Destination "C:/Windows/System32/"

    # macOS-Installation
    - name: Install d2 (macOS)
      if: runner.os == 'macOS'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        set -e
        gh release download ${{ inputs.version }} --repo terrastruct/d2 --pattern d2-${{ inputs.version }}-macos-amd64.tar.gz
        cat > sha.txt <<EOM
        7d8b3b5900d5609882d1a98fbb5c5a349332a706e0ef063b6db4aebdef09d274  d2-${{ inputs.version }}-macos-amd64.tar.gz
        EOM
        shasum -a 256 -c sha.txt
        tar xvf d2-${{ inputs.version }}-macos-amd64.tar.gz
        sudo cp d2-${{ inputs.version }}/bin/d2 /usr/local/bin